### UNION DE LOS DIFERENTES .CSV SCRAPEADOS (EVENTOS)

In [2]:
import requests as req
import re
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import time
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append('../src')

ESTE NOTEBOOK SE BASARÁ EN LA UNION Y UNA PEQUEÑA LIMPIEZA DE LOS DATAFRAMES RECOGIDOS A TRAVÉS DE WEBSCRAPING. 
- Webscraping elaborado en el Notebook de 'datos_import.ipynb'.

In [5]:
df0 = pd.read_csv('../data/dfs_entradas/df0.csv')

In [6]:
df0.head()

,Nombre,Fecha,Ubicacion,Precio,Enlace
0,El Rey León,2023-11-30T20:00:00.000+01:00,Teatro Lope de Vega,"desde 49,00 €",https://www.entradas.com/event/el-rey-leon-el-...
1,El Rey León,2023-12-01T18:00:00.000+01:00,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...
2,El Rey León,2023-12-01T22:00:00.000+01:00,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...
3,El Rey León,2023-12-02T18:00:00.000+01:00,Teatro Lope de Vega,"desde 67,00 €",https://www.entradas.com/event/el-rey-leon-el-...
4,El Rey León,2023-12-02T22:00:00.000+01:00,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...

In [8]:
df1 = pd.read_csv('../data/dfs_entradas/df1.csv')
df2 = pd.read_csv('../data/dfs_entradas/df2.csv')
df3 = pd.read_csv('../data/dfs_entradas/df3.csv')
df4 = pd.read_csv('../data/dfs_entradas/df4.csv')
df5 = pd.read_csv('../data/dfs_entradas/df5.csv')
df6 = pd.read_csv('../data/dfs_entradas/df6.csv')
df7 = pd.read_csv('../data/dfs_entradas/df7.csv')
df8 = pd.read_csv('../data/dfs_entradas/df8.csv')
df9 = pd.read_csv('../data/dfs_entradas/df9.csv')
df10 = pd.read_csv('../data/dfs_entradas/df10.csv')
df11 = pd.read_csv('../data/dfs_entradas/df11.csv')
df12 = pd.read_csv('../data/dfs_entradas/df12.csv')
df13 = pd.read_csv('../data/dfs_entradas/df13.csv')
df14 = pd.read_csv('../data/dfs_entradas/df14.csv')
df15 = pd.read_csv('../data/dfs_entradas/df15.csv')
df16 = pd.read_csv('../data/dfs_entradas/df16.csv')
df17 = pd.read_csv('../data/dfs_entradas/df17.csv')
df18 = pd.read_csv('../data/dfs_entradas/df18.csv')
df19 = pd.read_csv('../data/dfs_entradas/df19.csv')
df20 = pd.read_csv('../data/dfs_entradas/df20.csv')
df21 = pd.read_csv('../data/dfs_entradas/df21.csv')
df22 = pd.read_csv('../data/dfs_entradas/df22.csv')
df23 = pd.read_csv('../data/dfs_entradas/df23.csv')
df24 = pd.read_csv('../data/dfs_entradas/df24.csv')
df25 = pd.read_csv('../data/dfs_entradas/df25.csv')
df26 = pd.read_csv('../data/dfs_entradas/df26.csv')

In [9]:
df26.head()

,Nombre,Fecha,Ubicacion,Precio,Enlace
0,Concierto Sinfónico de Abono B12 (Viernes),2024-02-16T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1,Concierto Sinfónico de Abono A13 (Jueves),2024-02-22T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
2,Concierto Sinfónico de Abono A17 (Viernes),2024-04-12T19:30:00.000+02:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
3,Concierto Sinfónico de Abono B14 (Jueves),2024-02-29T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
4,Concierto Sinfónico de Abono B8 (Jueves),2024-01-11T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...

In [10]:
url = pd.concat([df0, df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, 
                df13, df14,df15, df16, df17, df18, df19, df20, df21, df22, df23, df24, df25, df26], 
                ignore_index = True)

In [11]:
url.head()

,Nombre,Fecha,Ubicacion,Precio,Enlace
0,El Rey León,2023-11-30T20:00:00.000+01:00,Teatro Lope de Vega,"desde 49,00 €",https://www.entradas.com/event/el-rey-leon-el-...
1,El Rey León,2023-12-01T18:00:00.000+01:00,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...
2,El Rey León,2023-12-01T22:00:00.000+01:00,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...
3,El Rey León,2023-12-02T18:00:00.000+01:00,Teatro Lope de Vega,"desde 67,00 €",https://www.entradas.com/event/el-rey-leon-el-...
4,El Rey León,2023-12-02T22:00:00.000+01:00,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...

In [15]:
url.tail(15)

,Nombre,Fecha,Ubicacion,Precio,Enlace
1691,Love Yarn Madrid,2024-02-10T10:00:00.000+01:00,Pabellón De Cristal Casa De Campo,"desde 10,00 €",https://www.entradas.com/event/love-yarn-madri...
1692,Love Yarn Madrid,2024-02-11T10:00:00.000+01:00,Pabellón De Cristal Casa De Campo,"desde 8,00 €",https://www.entradas.com/event/love-yarn-madri...
1693,Pack 3 días Love Yarn Madrid 2024,09/02/2024,Pabellón De Cristal Casa De Campo,"desde 28,00 €",https://www.entradas.com/event/love-yarn-madri...
1694,Concierto Sinfónico de Abono B16 (Jueves),2024-03-21T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1695,Concierto Sinfónico de Abono B16 (Viernes),2024-03-22T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1696,Concierto Sinfónico de Abono B18 (Jueves),2024-04-18T19:30:00.000+02:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1697,Concierto Sinfónico de Abono A15 (Viernes),2024-03-15T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1698,Concierto Sinfónico de Abono A19 (Viernes),2024-04-26T19:30:00.000+02:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1699,Concierto Sinfónico de Abono A15 (Jueves),2024-03-14T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1700,Concierto Sinfónico de Abono B18 (Viernes),2024-04-19T19:30:00.000+02:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1701,Concierto Sinfónico de Abono B12 (Viernes),2024-02-16T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1702,Concierto Sinfónico de Abono A13 (Jueves),2024-02-22T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1703,Concierto Sinfónico de Abono A17 (Viernes),2024-04-12T19:30:00.000+02:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1704,Concierto Sinfónico de Abono B14 (Jueves),2024-02-29T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...
1705,Concierto Sinfónico de Abono B8 (Jueves),2024-01-11T19:30:00.000+01:00,Teatro Monumental,"desde 15,00 €",https://www.entradas.com/event/concierto-sinfo...

In [16]:
len(url)

1706

In [21]:
num_duplicates = url.Enlace.duplicated().value_counts()
num_duplicates

Enlace
False    1692
True       14
Name: count, dtype: int64

In [22]:
#Elimino aquellas filas en las que el enlace al evento se repite, ya que entiendo que podría ensuciarnos los datos. 

url.drop_duplicates(subset='Enlace', inplace=True)

In [24]:
len(url)

1692

In [25]:
# Escribe los nombres de las columnas en minusculas

url.columns = url.columns.str.lower()

In [30]:
# Eliminamos esta fila, ya que contiene un pack que no nos interesa y podría darnos problemas.

indice_a_eliminar = 1693
url = url.drop(indice_a_eliminar)

# Para que los índices se reorganicen después de eliminar la fila
url.reset_index(drop=True, inplace=True)

In [34]:
# La columna 'fecha' la pasamos a datetime y así podremos hacer los cambios que queremos.
# como tengo año, mes, dia y hora, voy a separarlo todo, de momento. 

url['fecha'] = pd.to_datetime(url['fecha'], utc=True)

In [35]:
url['año'] = url['fecha'].dt.year
url['mes'] = url['fecha'].dt.month
url['dia'] = url['fecha'].dt.day
url['hora'] = url['fecha'].dt.time

In [39]:
# ELIMINO LA COLUMNA DE FECHA

url.drop('fecha', axis=1, inplace=True)

In [40]:
url.head()

,nombre,ubicacion,precio,enlace,año,mes,dia,hora
0,El Rey León,Teatro Lope de Vega,"desde 49,00 €",https://www.entradas.com/event/el-rey-leon-el-...,2023,11,30,19:00:00
1,El Rey León,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...,2023,12,1,17:00:00
2,El Rey León,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...,2023,12,1,21:00:00
3,El Rey León,Teatro Lope de Vega,"desde 67,00 €",https://www.entradas.com/event/el-rey-leon-el-...,2023,12,2,17:00:00
4,El Rey León,Teatro Lope de Vega,"desde 45,00 €",https://www.entradas.com/event/el-rey-leon-el-...,2023,12,2,21:00:00

In [41]:
url_clean = url.copy()

In [44]:
# LIMPIO LA COLUMNA 'precio' Y LE ELIMINO EL "desde"

url_clean['precio'] = url_clean['precio'].str.replace('desde', '').str.replace(',', '.').str.strip()

url_clean.head()

,nombre,ubicacion,precio,enlace,año,mes,dia,hora
0,El Rey León,Teatro Lope de Vega,49.00 €,https://www.entradas.com/event/el-rey-leon-el-...,2023,11,30,19:00:00
1,El Rey León,Teatro Lope de Vega,45.00 €,https://www.entradas.com/event/el-rey-leon-el-...,2023,12,1,17:00:00
2,El Rey León,Teatro Lope de Vega,45.00 €,https://www.entradas.com/event/el-rey-leon-el-...,2023,12,1,21:00:00
3,El Rey León,Teatro Lope de Vega,67.00 €,https://www.entradas.com/event/el-rey-leon-el-...,2023,12,2,17:00:00
4,El Rey León,Teatro Lope de Vega,45.00 €,https://www.entradas.com/event/el-rey-leon-el-...,2023,12,2,21:00:00

In [46]:
len(url_clean)

1691

In [52]:
url_clean.to_csv('../data/ENTRADAS.csv', index=False, encoding='utf-8')